/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainsw;

import java.awt.Dimension;
import java.awt.FlowLayout;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.util.ArrayList;

import java.util.List;
import javax.swing.DefaultListModel;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

import javax.swing.JTable;
import javax.swing.JTextArea;

import javax.swing.JTextField;

import javax.swing.ListSelectionModel;

import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Luciano Limina
 */
public class GUI extends javax.swing.JFrame {

    /* UC1 Gestisci Stazione */
    private TrainSW trainSw = TrainSW.getIstanza();
    List<Fermata> listSt = new ArrayList<Fermata>();
    List<Tratta> listTrSA = new ArrayList<Tratta>();
    List<Promozione> promoList = new ArrayList<Promozione>();
    Biglietto biglietto = new Biglietto();
    Tessera tex1;

    Tessera tessera;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Startup startup = new Startup(trainSw);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        gestisciSt = new javax.swing.JMenuItem();
        gestisciDep = new javax.swing.JMenuItem();
        gestisciColl = new javax.swing.JMenuItem();
        gestisciTr = new javax.swing.JMenuItem();
        gestisciPercorso = new javax.swing.JMenuItem();
        gestisciTratta = new javax.swing.JMenuItem();
        gestisciSoloAndata = new javax.swing.JMenuItem();
        gestisciAbbonamento = new javax.swing.JMenuItem();
        gestisciTessera = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        acquistoconTessera = new javax.swing.JMenuItem();
        acquistoconPunti = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome to TrainSW");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Press TrainSw to Start");

        jLabel3.setText("Progetto Ingegneria del Software 2016-2017");

        jLabel4.setText("Limina Luciano , Longhitano Andrea , Previti Luis");

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 102));

        jMenu1.setText("TrainSW");

        gestisciSt.setText("Gestisci Stazione");
        gestisciSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciStActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciSt);

        gestisciDep.setText("Gestisci Deposito");
        gestisciDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciDepActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciDep);

        gestisciColl.setText("Gestisci Collegamento");
        gestisciColl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciCollActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciColl);

        gestisciTr.setText("Gestisci Treno");
        gestisciTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciTrActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciTr);

        gestisciPercorso.setText("Gestisci Percorso");
        gestisciPercorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciPercorsoActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciPercorso);

        gestisciTratta.setText("Gestisci Tratta");
        gestisciTratta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciTrattaActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciTratta);

        gestisciSoloAndata.setText("Gestisci Solo-Andata");
        gestisciSoloAndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciSoloAndataActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciSoloAndata);

        gestisciAbbonamento.setText("Gestisci Abbonamento");
        gestisciAbbonamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciAbbonamentoActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciAbbonamento);

        gestisciTessera.setText("Gestisci Tessera");
        gestisciTessera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestisciTesseraActionPerformed(evt);
            }
        });
        jMenu1.add(gestisciTessera);

        jMenu2.setText("Gestisci Acquisto");

        acquistoconTessera.setText("Acquisto con Tessera");
        acquistoconTessera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquistoconTesseraActionPerformed(evt);
            }
        });
        jMenu2.add(acquistoconTessera);

        acquistoconPunti.setText("Acquisto con Punti");
        acquistoconPunti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquistoconPuntiActionPerformed(evt);
            }
        });
        jMenu2.add(acquistoconPunti);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("About");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestisciDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciDepActionPerformed
        JFrame gst = new JFrame("Gestisci Deposito");
        gst.setVisible(true);
        gst.setSize(300, 200);
        JPanel pan = new JPanel(new FlowLayout());
        pan.setVisible(true);

        JButton addDp = new JButton("Aggiungi Deposito");
        JButton viewDp = new JButton("Visualizza Depositi");

        gst.add(pan);

        pan.add(addDp);
        pan.add(viewDp);

        addDp.setLocation(0, 100);

        addDp.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                addDepFrame addDepframe = new addDepFrame();
                addDepframe.setVisible(true);

            }
        });

        viewDp.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JFrame viewObj = new JFrame("Visualizza Depositi");
                JPanel pan = new JPanel(new FlowLayout());
                Ferrovia ferrovia = trainSw.getFerrovia();

                String[] columnNames = {"ID deposito",
                    "Nome Stazione",
                    "Num posti"

                };

                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                dtm.setColumnIdentifiers(columnNames);
                viewObj.add(pan);

                viewObj.setSize(500, 400);
                viewObj.setVisible(true);

                Session session = new NewHibernateUtil().getSessionFactory().openSession();
                session.beginTransaction();

                for (Stazione stazione : ferrovia.getStazioni()) {

                    Deposito dp = stazione.getDeposito();
                    if (dp != null) {
                        dtm.addRow(new Object[]{dp.getId_dep(), stazione.getNome_stazione(), dp.getNumPosti()});
                    }
                }
                Tab.setModel(dtm);
                pan.add(new JScrollPane(Tab));
                pan.setVisible(true);
                session.getTransaction().commit();
                session.close();
            }
        });


    }//GEN-LAST:event_gestisciDepActionPerformed

    private void gestisciTrattaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciTrattaActionPerformed

        addTrattaFrame addTrframe = new addTrattaFrame();
        addTrframe.setVisible(true);
    }//GEN-LAST:event_gestisciTrattaActionPerformed

    private void gestisciSoloAndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciSoloAndataActionPerformed

        final JFrame frame = new JFrame();
        JPanel pan = new JPanel();
        JLabel lab1 = new JLabel("Inserisci nome stazioni");
        final JTextField txt_idStaPSA = new JTextField(10);
        final JTextField txt_idStaASA = new JTextField(10);
        JButton nextSA_button = new JButton("Avanti");
        pan.add(lab1);
        pan.add(txt_idStaPSA);
        pan.add(txt_idStaASA);
        pan.add(nextSA_button);
        trainSw.gestisciSoloAndata();
        frame.add(pan);
        frame.setSize(250, 150);
        frame.setVisible(true);

        nextSA_button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                listTrSA = trainSw.inserisciStazioneArrivo(txt_idStaPSA.getText(), txt_idStaASA.getText());

                String[] columnNames = {"ID Tratta",
                     "Tipo Treno",
                    "Posti disponibili prima",
                    "Posti disponibili seconda",
                     "Prezzo Base 1 Classe",
                    "Prezzo Base 2 Classe",
                 
                    "Fermata",
                    "Orario"
                   
                    
                       
                };

                final JTable perTab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                dtm.setColumnIdentifiers(columnNames);
                perTab.setModel(dtm);
                 Session session = NewHibernateUtil.getSessionFactory().openSession();
                 session.beginTransaction();
                for (Tratta tratta : listTrSA) {
                    tratta=(Tratta) session.load(Tratta.class, tratta.getId_tra());
                    for(FermataOrario fermata: tratta.getFermate()){
                    dtm.addRow(new Object[]{
                        tratta.getId_tratta(),tratta.getTreno().getTt().getTt_name(),
                        fermata.getNp_1c(),fermata.getNp_2c(),
                        tratta.getTreno().getTt().getPrezzo_prima(),tratta.getTreno().getTt().getPrezzo_seconda(),
                        fermata.getFermata().getStazione().getNome_stazione(),fermata.getOrario()
                    });

                }
                }
                session.getTransaction().commit();
                session.close();
                frame.dispose();
                  
                perTab.getColumnModel().getColumn(7).setMinWidth(150);
                final JFrame tabfram = new JFrame("Scegli la tratta");
                tabfram.setSize(1000, 450);
               
                perTab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                JButton nextSAButton = new JButton("Avanti");
                JButton endButton = new JButton("Fine");
                final JTextField txt_class = new JTextField(2);
                
                JPanel panst = new JPanel(new FlowLayout());
                  panst.setSize(new Dimension(850, 350));
                panst.add(txt_class);
                panst.add(new JScrollPane(perTab));
                panst.add(nextSAButton);
                panst.add(endButton);
                tabfram.add(panst);
                tabfram.setVisible(true);

                nextSAButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {

                        tabfram.dispose();
                        Tratta trattasx=null;
                       
                        int i = (int)perTab.getValueAt((int) perTab.getSelectedRow(),0);
                       for(Tratta tr: listTrSA)
                           if(tr.getId_tra()==i)
                               trattasx=tr;
               
                        
                        int classe;
                        classe = new Integer(txt_class.getText());
                        Biglietto biglietto;
                        biglietto = trainSw.scegliTratta(trattasx, classe);

                        final JFrame confBiglietto = new JFrame("Visualizza Biglietto");
                        JPanel pan = new JPanel(new FlowLayout());
                        JButton confButtonBiglietto = new JButton("Conferma");
                        JLabel bigliettoLab = new JLabel(biglietto.toString());
                       
                        pan.add(bigliettoLab);
                       
                        pan.add(confButtonBiglietto);
                        confBiglietto.add(pan);
                        confBiglietto.setVisible(true);
                        confBiglietto.setSize(700, 100);

                        confButtonBiglietto.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                trainSw.ConfermaBiglietto();
                                confBiglietto.dispose();
                            }
                        });

                    }
                });

            }
        });
    }//GEN-LAST:event_gestisciSoloAndataActionPerformed

    private void gestisciTesseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciTesseraActionPerformed
        
        final JFrame gestisciTessera = new JFrame();
        JPanel gestPan = new JPanel(new FlowLayout());
        JButton addTess = new JButton("Aggiungi  tessera");
        JButton viewTess = new JButton("Visualizza tessere ");
        
        gestPan.add(addTess);
        gestPan.add(viewTess);
        gestisciTessera.add(gestPan);
        
        gestisciTessera.setSize(200,150);
        gestisciTessera.setVisible(true);
        
        addTess.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 insClienteFrame inClienteframe = new insClienteFrame();
        inClienteframe.setVisible(true);
        gestisciTessera.dispose();
            }
        });
       
        
        viewTess.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
        
                
                 JFrame viewObj = new JFrame("Visualizza Tessere");
                JPanel pan = new JPanel(new FlowLayout());
               
                DefaultListModel demod = new DefaultListModel();
                JList viewList = new JList(demod);
                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);
                viewObj.add(pan);
                pan.add(viewList);
                String[] columnNames = {"id tessera",
                    "punti",
                    " nome intestatario",
                    " cognome intestatario",
                    "data rilascio",
                    "data scadenza"
                };
                viewObj.setSize(600, 350);
                viewObj.setVisible(true);
                dtm.setColumnIdentifiers(columnNames);
                for (Tessera tessera : trainSw.getTessere_registrate()) {
                    dtm.addRow(new Object[]{tessera.getId_tessera(),
                        tessera.getPunti() , tessera.getCliente().getNome() ,
                        tessera.getCliente().getCognome() ,
                        tessera.getD_rilascio().toString(),
                        tessera.getD_scadenza().toString()
                    });

                }
                Tab.setModel(dtm);
                pan.setVisible(true);
                pan.add(new JScrollPane(Tab));
            }

                
            
            
        });
        
        
        
        
    }//GEN-LAST:event_gestisciTesseraActionPerformed

    private void gestisciStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciStActionPerformed

        JFrame gst = new JFrame("Gestisci Stazione");
        gst.setVisible(true);
        gst.setSize(300, 200);
        JPanel pan = new JPanel(new FlowLayout());
        pan.setVisible(true);

        JButton addSt = new JButton("Aggiungi Stazione");
        JButton viewSt = new JButton("Visualizza Stazioni");

        gst.add(pan);

        pan.add(addSt);
        pan.add(viewSt);

        addSt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                addStFrame addStframe = new addStFrame();
                addStframe.setVisible(true);

            }
        });

        viewSt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JFrame viewObj = new JFrame("Visualizza Stazioni");
                JPanel pan = new JPanel(new FlowLayout());
                Ferrovia ferrovia = trainSw.getFerrovia();
                DefaultListModel demod = new DefaultListModel();
                JList viewList = new JList(demod);
                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);
                viewObj.add(pan);
                pan.add(viewList);
                String[] columnNames = {"ID Stazione",
                    "Num bin",
                    "Locazione",
                    "Nome stazione"
                };
                viewObj.setSize(600, 350);
                viewObj.setVisible(true);
                dtm.setColumnIdentifiers(columnNames);
                for (Stazione stazione : ferrovia.getStazioni()) {
                    dtm.addRow(new Object[]{stazione.getId_stazione(),
                        stazione.getNum_bin(), stazione.getLocazione(), stazione.getNome_stazione()
                    });

                }
                Tab.setModel(dtm);
                pan.setVisible(true);
                pan.add(new JScrollPane(Tab));
            }
        });


    }//GEN-LAST:event_gestisciStActionPerformed

    private void gestisciCollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciCollActionPerformed

        JFrame gst = new JFrame("Gestisci Collegamento");
        gst.setVisible(true);
        gst.setSize(300, 200);
        JPanel pan = new JPanel(new FlowLayout());
        pan.setVisible(true);

        JButton addCol = new JButton("Aggiungi Collegamento");
        JButton viewCol = new JButton("Visualizza Collegamenti");

        gst.add(pan);

        pan.add(addCol);
        pan.add(viewCol);

        addCol.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                AddCollFrame addCollframe = new AddCollFrame();
                addCollframe.setVisible(true);

            }
        });

        viewCol.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame viewObj = new JFrame("Visualizza Collegamenti");
                JPanel pan = new JPanel(new FlowLayout());
                Ferrovia ferrovia = trainSw.getFerrovia();

                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);
                viewObj.add(pan);

                String[] columnNames = {"ID Collegamento",
                    "distanza",
                    "Stazione_a",
                    "Stazione_b"
                };
                viewObj.setSize(600, 350);
                viewObj.setVisible(true);
                Session session = new NewHibernateUtil().getSessionFactory().openSession();
                session.beginTransaction();
                dtm.setColumnIdentifiers(columnNames);
                for (Collegamento collegamento : ferrovia.getCollegamenti()) {
                    collegamento = (Collegamento) session.load(Collegamento.class, collegamento.getId_collegamento());
                    dtm.addRow(new Object[]{
                        collegamento.getId_collegamento(), collegamento.getDistanza(), collegamento.getStazione_a().getNome_stazione(),
                        collegamento.getStazione_b().getNome_stazione()
                    });
                }
                Tab.setModel(dtm);
                pan.add(new JScrollPane(Tab));
                pan.setVisible(true);
                session.getTransaction().commit();
                session.close();
            }
        });

    }//GEN-LAST:event_gestisciCollActionPerformed

    private void gestisciTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciTrActionPerformed
        JFrame gst = new JFrame("Gestisci Treno");
        gst.setVisible(true);
        gst.setSize(300, 200);
        JPanel pan = new JPanel(new FlowLayout());
        pan.setVisible(true);

        JButton add = new JButton("Aggiungi Tipologia Treno");
        JButton view = new JButton("Visualizza Tipologia");

        gst.add(pan);

        pan.add(add);
        pan.add(view);

        add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddTipologiaTrenoFrame addTTframe = new AddTipologiaTrenoFrame();
                addTTframe.setVisible(true);
            }

        });
        view.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame viewObj = new JFrame("Visualizza Tipologia");
                JPanel pan = new JPanel(new FlowLayout());
                Ferrovia ferrovia = trainSw.getFerrovia();

                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);
                viewObj.add(pan);

                String[] columnNames = {"ID Tipologia",
                    "Nome Tipologia",
                    "Posti letto",
                    "Posti Prima Classe",
                    "Posti Seconda Classe",
                    "Velocita",
                    "Prezzo Prima",
                    "Prezzo Seconda"
                };
                viewObj.setSize(600, 350);
                viewObj.setVisible(true);
                dtm.setColumnIdentifiers(columnNames);
                for (TipoTreno tipo : ferrovia.getTipoTreno()) {
                    dtm.addRow(new Object[]{
                        tipo.getId_tt(), tipo.getTt_name(), tipo.getPosti_letto(), tipo.getNp_1c(),
                        tipo.getNp_2c(), tipo.getVelocita(), tipo.getPrezzo_prima(), tipo.getPrezzo_seconda()
                    });
                }
                Tab.setModel(dtm);
                pan.add(new JScrollPane(Tab));
                pan.setVisible(true);
            }
        });
    }//GEN-LAST:event_gestisciTrActionPerformed

    private void gestisciPercorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciPercorsoActionPerformed
        trainSw.GestisciPercorso();

        JFrame gst = new JFrame("Gestisci Percorso");
        gst.setVisible(true);
        gst.setSize(300, 200);
        JPanel pan = new JPanel(new FlowLayout());
        pan.setVisible(true);

        JButton add = new JButton("Aggiungi Percorso");
        JButton view = new JButton("Visualizza Percorsi");

        gst.add(pan);

        pan.add(add);
        pan.add(view);
        view.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame viewObj = new JFrame("Visualizza Percorsi");
                JPanel pan = new JPanel(new FlowLayout());
                Ferrovia ferrovia = trainSw.getFerrovia();

                final JTable Tab = new JTable();
                final DefaultTableModel dtm = new DefaultTableModel(0, 0);
                viewObj.add(pan);

                String[] columnNames = {"ID Percorso",
                    "Nome Fermata Stazione",
                    "Distanza Parziale"

                };
                viewObj.setSize(600, 350);
                viewObj.setVisible(true);
                dtm.setColumnIdentifiers(columnNames);
                Session session = new NewHibernateUtil().getSessionFactory().openSession();
                session.beginTransaction();
                for (Percorso per : ferrovia.getPercorsi()) {
                    for (Fermata fer : per.getFermate()) {
                        fer = (Fermata) session.load(Fermata.class, fer.getId_fer());
                        Stazione st=(Stazione) session.load(Stazione.class,fer.getStazione().getId_stazione() );
                        dtm.addRow(new Object[]{
                            per.getId_per(), st.getNome_stazione(), fer.getDistanza_p()
                        });
                    }
                }
                session.getTransaction().commit();
                session.close();
                Tab.setModel(dtm);
                pan.add(new JScrollPane(Tab));
                pan.setVisible(true);
            }
        });

        add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                final JFrame frame = new JFrame("Inserisci Percorso");
                frame.setVisible(true);
                JPanel pan = new JPanel(new FlowLayout());
                trainSw.GestisciPercorso();
                JLabel lab = new JLabel("Inserisci nomi stazioni partenza e arrivo");
                final JTextField txt_sta1;
                final JTextField txt_sta2;
                txt_sta1 = new JTextField(10);
                txt_sta2 = new JTextField(10);
                JButton nextButton = new JButton("Prosegui");
                JButton annullaButton = new JButton("Annulla");
                pan.add(lab);
                pan.add(txt_sta1);
                pan.add(txt_sta2);
                pan.add(nextButton);
                pan.add(annullaButton);
                frame.setSize(300, 200);
                frame.add(pan);

                annullaButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {

                        frame.dispose();
                    }
                });
                nextButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        frame.dispose();
                        String idStazA, idStazB;
                        idStazA = txt_sta1.getText();
                        idStazB = txt_sta2.getText();

                        listSt = trainSw.InserisciStazioni(idStazA, idStazB);

                        if (listSt == null) {
                            JOptionPane.showMessageDialog(frame, "Stazioni non presenti", "Errore", JOptionPane.ERROR_MESSAGE);
                        } else {
                            final JTable Tab = new JTable();
                            final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                            String[] columnNames = {"ID Fermata",
                                "Nome Fermata Stazione",
                                "Distanza Parziale"

                            };
                            dtm.setColumnIdentifiers(columnNames);
                            //Aggiungere elementi lista nella tabella
                            Session session = NewHibernateUtil.getSessionFactory().openSession();
                            session.beginTransaction();

                            for (Fermata fer : listSt) {
                               Stazione st = (Stazione) session.load(Stazione.class, fer.getStazione().getId_stazione());
                                dtm.addRow(new Object[]{
                                    fer.getId_stazione(), st.getNome_stazione(), fer.getDistanza_p()

                                });
                            }
                            session.getTransaction().commit();
                            session.close();
                            Tab.setModel(dtm);
                            final JFrame tabfram = new JFrame("Scegli le fermate");
                            tabfram.setSize(1000, 1000);

                            Tab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

                            JButton nextButton = new JButton("Avanti");
                            JButton endButton = new JButton("Fine");
                            JPanel panst = new JPanel(new FlowLayout());
                            panst.add(new JScrollPane(Tab));
                            panst.add(nextButton);
                            panst.add(endButton);
                            tabfram.add(panst);
                            tabfram.setVisible(true);

                            nextButton.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {

                                    Fermata sts;
                                    sts = listSt.get((int) Tab.getSelectedRow());
                                    
                                    trainSw.InserisciFermata(sts);

                                }
                            });

                            endButton.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    trainSw.ConfermaPercorso();

                                    tabfram.dispose();

                                }
                            });

                        }
                    }
                });
            }
        });
    }


//GEN-LAST:event_gestisciPercorsoActionPerformed
    private void gestisciAbbonamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestisciAbbonamentoActionPerformed
        /* Gestisci Abbonamento */
        gestAbbonamento gestAbbonamento1 = new gestAbbonamento();
        gestAbbonamento1.setVisible(true);


    }//GEN-LAST:event_gestisciAbbonamentoActionPerformed

    private void acquistoconTesseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquistoconTesseraActionPerformed

        JFrame insTess = new JFrame("Inserimento Tessera");
        JPanel panTess = new JPanel(new FlowLayout());
        JLabel labtess = new JLabel("Inserisci id Tessera");
        final JTextArea txt_tess = new JTextArea();
        txt_tess.setColumns(3);
        JButton buttonTess = new JButton("Esegui");

        panTess.add(labtess);
        panTess.add(txt_tess);
        panTess.add(buttonTess);

        insTess.add(panTess);
        insTess.setVisible(true);
        insTess.setSize(200, 300);

        buttonTess.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Tessera tex1 = null;

                Integer id_tessera;
                id_tessera = new Integer(txt_tess.getText());

                for (Tessera tex : trainSw.getTessere_registrate()) {
                    if (tex.getId_tessera() == id_tessera) {
                        tex1 = tex;
                    }
                }
                if (tex1 != null) {

                    /**
                     * **********************************************
                     *
                     * Acquisto Biglietto
                     * ********************************************
                     */
                    trainSw.InserisciTessera(tex1);

                    final JFrame frame = new JFrame();
                    JPanel pan = new JPanel();
                    JLabel lab1 = new JLabel("Inserisci id stazioni");
                    final JTextField txt_idStaPSA = new JTextField(10);
                    final JTextField txt_idStaASA = new JTextField(10);
                    JButton nextSA_button = new JButton("Avanti");
                    pan.add(lab1);
                    pan.add(txt_idStaPSA);
                    pan.add(txt_idStaASA);
                    pan.add(nextSA_button);
                    trainSw.gestisciSoloAndata();
                    frame.add(pan);
                    frame.setSize(150, 200);
                    frame.setVisible(true);

                    nextSA_button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            String id_sta_PSA = txt_idStaPSA.getText();
                            String id_sta_ASA = txt_idStaASA.getText();
                            listTrSA = trainSw.inserisciStazioneArrivo(id_sta_PSA, id_sta_ASA);

                            String[] columnNames = {"ID Tratta",
                                "Data partenza",
                                "Data arrivo",
                                " Stazione partenza",
                                "Stazione arrivo"

                            };

                            final JTable perTab = new JTable();
                            final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                            dtm.setColumnIdentifiers(columnNames);
                            perTab.setModel(dtm);

                            for (Tratta tratta : listTrSA) {

                                dtm.addRow(new Object[]{
                                    tratta.getId_tratta(), tratta.getData_p().toString(), tratta.getData_a().toString(), tratta.getPercorso().getStaz_par(), tratta.getPercorso().getStaz_arr()

                                });

                            }

                            frame.dispose();

                            final JFrame tabfram = new JFrame("Inserisci la classe e scegli la tratta");
                            tabfram.setSize(500, 200);

                            perTab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

                            JButton nextSAButton = new JButton("Avanti");
                            JButton endButton = new JButton("Fine");
                            final JTextField txt_class = new JTextField(2);

                            JPanel panst = new JPanel(new FlowLayout());
                            panst.add(txt_class);
                            panst.add(perTab);
                            panst.add(nextSAButton);
                            panst.add(endButton);
                            tabfram.add(panst);
                            tabfram.setVisible(true);

                            nextSAButton.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {

                                    tabfram.dispose();
                                    Tratta trattasx;
                                    trattasx = listTrSA.get((int) perTab.getSelectedRow());
                                    int classe;
                                    classe = new Integer(txt_class.getText());
                                    Biglietto biglietto;
                                    biglietto = trainSw.scegliTratta(trattasx, classe);

                                    final JFrame confBiglietto = new JFrame("Visualizza Biglietto");
                                    JPanel pan = new JPanel(new FlowLayout());
                                    JButton confButtonBiglietto = new JButton("Conferma");
                                    JLabel bigliettoLab = new JLabel(biglietto.toString());
                                    pan.add(bigliettoLab);
                                    pan.add(confButtonBiglietto);
                                    confBiglietto.add(pan);
                                    confBiglietto.setVisible(true);
                                    confBiglietto.setSize(500, 100);

                                    confButtonBiglietto.addActionListener(new ActionListener() {
                                        @Override
                                        public void actionPerformed(ActionEvent e) {
                                            trainSw.confermaBigliettoTessera();
                                            confBiglietto.dispose();
                                        }
                                    });

                                }
                            });

                        }
                    });
                }
            }
        });


    }//GEN-LAST:event_acquistoconTesseraActionPerformed

    private void acquistoconPuntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquistoconPuntiActionPerformed
        // TODO add your handling code here:

        JFrame insTess = new JFrame("Inserisci id tessera");
        JPanel panTess = new JPanel(new FlowLayout());
        JLabel labTess = new JLabel("Inserisci id tessera");
        final JTextArea txtTess = new JTextArea();
        txtTess.setColumns(3);
        JButton buttonTess = new JButton("Esegui");

        panTess.add(labTess);
        panTess.add(txtTess);
        panTess.add(buttonTess);

        insTess.add(panTess);
        insTess.setSize(200, 150);
        insTess.setVisible(true);

        buttonTess.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tex1 = null;
                Integer id_tessera = new Integer(txtTess.getText());
                for (Tessera tex : trainSw.getTessere_registrate()) {
                    if (tex.getId_tessera() == id_tessera) {
                        tex1 = tex;
                    }
                }
                if (tex1 != null) {

                    trainSw.InserisciTessera(tex1);
                    System.out.println(tex1);
                    final JFrame frame = new JFrame("Acquista biglietto");
                    JLabel lab1 = new JLabel("Inserisci nome stazioni");
                    JPanel pan = new JPanel(new FlowLayout());
                    final JTextField txt_idStaPSA = new JTextField(10);
                    final JTextField txt_idStaASA = new JTextField(10);
                    JButton nextSA_button = new JButton("Avanti");
                    pan.add(lab1);
                    pan.add(txt_idStaPSA);
                    pan.add(txt_idStaASA);
                    pan.add(nextSA_button);
                    trainSw.gestisciSoloAndata();
                    frame.add(pan);
                    frame.setSize(250, 150);
                    frame.setVisible(true);

                    nextSA_button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            String id_sta_PSA = txt_idStaPSA.getText();
                            String id_sta_ASA = txt_idStaASA.getText();
                            listTrSA = trainSw.inserisciStazioneArrivo(id_sta_PSA, id_sta_ASA);

                            String[] columnNames = {"ID Tratta",
                                "Data partenza",
                                "Data arrivo",
                                " Stazione partenza",
                                "Stazione arrivo"

                            };

                            final JTable perTab = new JTable();
                            final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                            dtm.setColumnIdentifiers(columnNames);
                            perTab.setModel(dtm);

                            for (Tratta tratta : listTrSA) {

                                dtm.addRow(new Object[]{
                                    tratta.getId_tratta(), tratta.getData_p().toString(), tratta.getData_a().toString(), tratta.getPercorso().getStaz_par(), tratta.getPercorso().getStaz_arr()

                                });

                            }

                            frame.dispose();

                            final JFrame tabfram = new JFrame("Scegli la tratta e inserisci la classe desiderata");
                            tabfram.setSize(600, 140);

                            perTab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

                            JButton nextSAButton = new JButton("Avanti");
                            JButton endButton = new JButton("Fine");
                            final JTextField txt_class = new JTextField(2);
                            txt_class.setName("classe");

                            JPanel panst = new JPanel(new FlowLayout());
                            panst.add(txt_class);
                            panst.add(perTab);
                            panst.add(nextSAButton);
                            panst.add(endButton);
                            tabfram.add(panst);
                            tabfram.setVisible(true);

                            nextSAButton.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {

                                    tabfram.dispose();
                                    Tratta trattasx;
                                    trattasx = listTrSA.get((int) perTab.getSelectedRow());
                                    int classe;
                                    classe = new Integer(txt_class.getText());

                                    biglietto = trainSw.scegliTratta(trattasx, classe);
                                    System.out.println(biglietto);

                                    final JFrame confBiglietto = new JFrame("Visualizza Biglietto");
                                    JPanel pan = new JPanel(new FlowLayout());
                                    JButton confButtonBiglietto = new JButton("Conferma");
                                    JLabel bigliettoLab = new JLabel(biglietto.toString());
                                    pan.add(bigliettoLab);
                                    pan.add(confButtonBiglietto);
                                    confBiglietto.add(pan);
                                    confBiglietto.setVisible(true);
                                    confBiglietto.setSize(560, 100);

                                    confButtonBiglietto.addActionListener(new ActionListener() {
                                        @Override
                                        public void actionPerformed(ActionEvent e) {
                                            promoList = trainSw.visualizzaPromozioni();
                                            confBiglietto.dispose();
                                            /*Visualizzare le promozioni */

                                            String[] columnNames = {
                                                "Nome promozione",
                                                "Punti"

                                            };

                                            final JTable promoTab = new JTable();
                                            final DefaultTableModel dtm = new DefaultTableModel(0, 0);

                                            dtm.setColumnIdentifiers(columnNames);
                                            promoTab.setModel(dtm);

                                            for (Promozione promo : promoList) {

                                                dtm.addRow(new Object[]{
                                                    promo.getNome(), promo.getSogliaPunti()

                                                });

                                            }

                                            final JFrame tabframPromo = new JFrame("Scegli la promozione");

                                            promoTab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

                                            JButton nextButtonPromo = new JButton("Avanti");
                                            JButton endButtonPromo = new JButton("Fine");
                                            JPanel panPromo = new JPanel(new FlowLayout());
                                            panPromo.add(promoTab);
                                            panPromo.add(nextButtonPromo);
                                            panPromo.add(endButtonPromo);
                                            tabframPromo.add(panPromo);
                                            tabframPromo.setVisible(true);
                                            tabframPromo.setSize(500, 200);

                                            endButtonPromo.addActionListener(new ActionListener() {
                                                @Override
                                                public void actionPerformed(ActionEvent e) {
                                                    tabframPromo.dispose();
                                                }
                                            });

                                            nextButtonPromo.addActionListener(new ActionListener() {
                                                @Override
                                                public void actionPerformed(ActionEvent e) {
                                                    tabframPromo.dispose();
                                                    Promozione promo2;
                                                    promo2 = promoList.get((int) perTab.getSelectedRow());
                                                    System.out.println(promo2);
                                                    final Double prezzoScont;

                                                    prezzoScont = trainSw.AssociaPromozione(promo2);
                                                    System.out.println(prezzoScont);

                                                    final JFrame confPrezzo = new JFrame("Conferma Prezzo");
                                                    JPanel panPrezzo = new JPanel(new FlowLayout());
                                                    JLabel prezzoLab = new JLabel(prezzoScont.toString());
                                                    JButton confPrezzoScont;
                                                    confPrezzoScont = new JButton("Conferma");

                                                    panPrezzo.add(prezzoLab);
                                                    panPrezzo.add(confPrezzoScont);
                                                    confPrezzo.add(panPrezzo);
                                                    confPrezzo.setVisible(true);
                                                    confPrezzo.setSize(200, 250);

                                                    confPrezzoScont.addActionListener(new ActionListener() {
                                                        @Override
                                                        public void actionPerformed(ActionEvent e) {
                                                            Biglietto biglietto;
                                                            biglietto = trainSw.ConfermaAcquistoPunti(prezzoScont);
                                                            JOptionPane.showMessageDialog(confPrezzo, biglietto.toString());
                                                            confPrezzo.dispose();
                                                        }
                                                    });

                                                }
                                            });

                                        }
                                    });

                                }
                            });

                        }
                    });
                }

            }
        }
        );
    }//GEN-LAST:event_acquistoconPuntiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acquistoconPunti;
    private javax.swing.JMenuItem acquistoconTessera;
    private javax.swing.JMenuItem gestisciAbbonamento;
    private javax.swing.JMenuItem gestisciColl;
    private javax.swing.JMenuItem gestisciDep;
    private javax.swing.JMenuItem gestisciPercorso;
    private javax.swing.JMenuItem gestisciSoloAndata;
    private javax.swing.JMenuItem gestisciSt;
    private javax.swing.JMenuItem gestisciTessera;
    private javax.swing.JMenuItem gestisciTr;
    private javax.swing.JMenuItem gestisciTratta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
